Loaded module: python3/3.6.2
./run.sh: line 5: 13925 Killed                  python3 dataset/make.py $raw_data_dir $data_dir $n_out_speakers $test_prop $sample_rate $n_utt_attr
Traceback (most recent call last):
  File "dataset/reduce.py", line 10, in <module>
    data = pickle.load(f)
EOFError: Ran out of input
Traceback (most recent call last):
  File "dataset/segments.py", line 14, in <module>
    data = pickle.load(f)
EOFError: Ran out of input
Traceback (most recent call last):
  File "dataset/segments.py", line 13, in <module>
    with open(pickle_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/work1/s183921/preprocessed_data/vae/spraakbanken/in_test.pkl'
Traceback (most recent call last):
  File "dataset/segments.py", line 13, in <module>
    with open(pickle_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/work1/s183921/preprocessed_data/vae/spraakbanken/out_test.pkl'
